name: Docker Build + Scan com o Trivy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Images
        run: |
          # Construir a imagem para homolog
          docker build -t seu_usuario_docker/ambiente-homolog -f Dockerfile .
          
          # Construir a imagem para produção
          docker build -t seu_usuario_docker/ambiente-prod -f Dockerfile .
          
          # Construir a imagem para teste
          docker build -t seu_usuario_docker/ambiente-teste -f Dockerfile .

      - name: Install Trivy
        run: |
          curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.28.0/trivy_0.28.0_Linux-64bit.tar.gz | tar xz -C /usr/local/bin --strip-components=1 trivy

      - name: Scan Docker Images with Trivy
        run: |
          # Escanear a imagem de homolog
          trivy image --no-progress seu_usuario_docker/ambiente-homolog
          
          # Escanear a imagem de produção
          trivy image --no-progress seu_usuario_docker/ambiente-prod
          
          # Escanear a imagem de teste
          trivy image --no-progress seu_usuario_docker/ambiente-teste
